alter table DROPS_INITIATIVE add constraint FK_DROPS_INITIATIVE_ON_PROJECT foreign key (PROJECT_ID) references DROPS_PROJECT(ID) on delete CASCADE;
create index IDX_DROPS_INITIATIVE_ON_PROJECT on DROPS_INITIATIVE (PROJECT_ID);
